#!/bin/sh /etc/rc.common
START=96
STOP=10
USE_PROCD=1
BASE_DIR="/overlay/tkounter"
APP_BIN="$BASE_DIR/tkounter"
BOOTSTRAP_FILE="/etc/tkounter/bootstrap.json"
start_service() {
  [ -x "$APP_BIN" ] || return 1
  procd_open_instance
  procd_set_param command "$APP_BIN"
  procd_set_param env TKOUNTER_BOOTSTRAP="$BOOTSTRAP_FILE"
  procd_set_param respawn 3600 5 5
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
